<?php
/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			12/15/2017
Description:	Creates the DAL class for  blog table and respective stored procedures

*/



class Blog {

	// This is for local purposes only! In hosted environments the db_settings.php file should be outside of the webroot, such as: include("/outside-webroot/db_settings.php");
	protected static function getDbSettings() { return "DAL/db_localsettings.php"; }

	/******************************************************************/
	// Properties
	/******************************************************************/

	protected $Id;
	protected $Title;
	protected $Description;
	protected $ImgUrl;
	protected $BlogCategoryId;
	protected $SecurityUserId;
	protected $CreateDate;
	protected $EditDate;


	/******************************************************************/
	// Constructors
	/******************************************************************/
	public function __construct() {
		$argv = func_get_args();
		switch( func_num_args() ) {
			case 0:
				self::__constructBase();
				break;
			case 1:
				self::__constructPK( $argv[0] );
				break;
			case 8:
				self::__constructFull( $argv[0], $argv[1], $argv[2], $argv[3], $argv[4], $argv[5], $argv[6], $argv[7] );
		}
	}


	public function __constructBase() {
		$this->Id = 0;
		$this->Title = "";
		$this->Description = "";
		$this->ImgUrl = "";
		$this->BlogCategoryId = 0;
		$this->SecurityUserId = 0;
		$this->CreateDate = "";
		$this->EditDate = "";
	}


	public function __constructPK($paramId) {
		$this->load($paramId);
	}


	public function __constructFull($paramId,$paramTitle,$paramDescription,$paramImgUrl,$paramBlogCategoryId,$paramSecurityUserId,$paramCreateDate,$paramEditDate) {
		$this->Id = $paramId;
		$this->Title = $paramTitle;
		$this->Description = $paramDescription;
		$this->ImgUrl = $paramImgUrl;
		$this->BlogCategoryId = $paramBlogCategoryId;
		$this->SecurityUserId = $paramSecurityUserId;
		$this->CreateDate = $paramCreateDate;
		$this->EditDate = $paramEditDate;
	}


	/******************************************************************/
	// Accessors / Mutators
	/******************************************************************/

	public function getId(){
		return $this->Id;
	}
	public function setId($value){
		$this->Id = $value;
	}
	public function getTitle(){
		return $this->Title;
	}
	public function setTitle($value){
		$this->Title = $value;
	}
	public function getDescription(){
		return $this->Description;
	}
	public function setDescription($value){
		$this->Description = $value;
	}
	public function getImgUrl(){
		return $this->ImgUrl;
	}
	public function setImgUrl($value){
		$this->ImgUrl = $value;
	}
	public function getBlogCategoryId(){
		return $this->BlogCategoryId;
	}
	public function setBlogCategoryId($value){
		$this->BlogCategoryId = $value;
	}
	public function getSecurityUserId(){
		return $this->SecurityUserId;
	}
	public function setSecurityUserId($value){
		$this->SecurityUserId = $value;
	}
	public function getCreateDate(){
		return $this->CreateDate;
	}
	public function setCreateDate($value){
		$this->CreateDate = $value;
	}
	public function getEditDate(){
		return $this->EditDate;
	}
	public function setEditDate($value){
		$this->EditDate = $value;
	}


	/******************************************************************/
	// Public Methods
	/******************************************************************/


	public function load($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_blog_Load(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);

		while ($row = $result->fetch_assoc()) {
		 $this->setId($row['Id']);
		 $this->setTitle($row['Title']);
		 $this->setDescription($row['Description']);
		 $this->setImgUrl($row['ImgUrl']);
		 $this->setBlogCategoryId($row['BlogCategoryId']);
		 $this->setSecurityUserId($row['SecurityUserId']);
		 $this->setCreateDate($row['CreateDate']);
		 $this->setEditDate($row['EditDate']);
		}
	}


	public function save() {
		if ($this->getId() == 0)
			$this->insert();
		else
			$this->update();
	}

	/******************************************************************/
	// Private Methods
	/******************************************************************/



	private function insert() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_blog_Add(?,?,?,?,?,?,?)');
		$arg1 = $this->getTitle();
		$arg2 = $this->getDescription();
		$arg3 = $this->getImgUrl();
		$arg4 = $this->getBlogCategoryId();
		$arg5 = $this->getSecurityUserId();
		$arg6 = $this->getCreateDate();
		$arg7 = $this->getEditDate();
		$stmt->bind_param('sssiiss',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		while ($row = $result->fetch_assoc()) {
			// By default, the DALGen generated INSERT procedure returns the scope identity as id
			$this->load($row['id']);
		}
	}


	private function update() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_blog_Update(?,?,?,?,?,?,?,?)');
		$arg1 = $this->getId();
		$arg2 = $this->getTitle();
		$arg3 = $this->getDescription();
		$arg4 = $this->getImgUrl();
		$arg5 = $this->getBlogCategoryId();
		$arg6 = $this->getSecurityUserId();
		$arg7 = $this->getCreateDate();
		$arg8 = $this->getEditDate();
		$stmt->bind_param('isssiiss',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7,$arg8);
		$stmt->execute();
	}

	private static function setNullValue($value){
		if ($value == "")
			return null;
		else
			return $value;
	}

	/******************************************************************/
	// Static Methods
	/******************************************************************/



	public static function loadall() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_blog_LoadAll()');
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$blog = new Blog($row['Id'],$row['Title'],$row['Description'],$row['ImgUrl'],$row['BlogCategoryId'],$row['SecurityUserId'],$row['CreateDate'],$row['EditDate']);
				$arr[] = $blog;
			}
			return $arr;
		}
		else {
			//die("The query yielded zero results.No rows found.");
		}
	}


	public static function remove($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_blog_Delete(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();
	}


	public static function search($paramId,$paramTitle,$paramDescription,$paramImgUrl,$paramBlogCategoryId,$paramSecurityUserId,$paramCreateDate,$paramEditDate) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_blog_Search(?,?,?,?,?,?,?,?)');
		$arg1 = Blog::setNullValue($paramId);
		$arg2 = Blog::setNullValue($paramTitle);
		$arg3 = Blog::setNullValue($paramDescription);
		$arg4 = Blog::setNullValue($paramImgUrl);
		$arg5 = Blog::setNullValue($paramBlogCategoryId);
		$arg6 = Blog::setNullValue($paramSecurityUserId);
		$arg7 = Blog::setNullValue($paramCreateDate);
		$arg8 = Blog::setNullValue($paramEditDate);
		$stmt->bind_param('isssiiss',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7,$arg8);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$blog = new Blog($row['Id'],$row['Title'],$row['Description'],$row['ImgUrl'],$row['BlogCategoryId'],$row['SecurityUserId'],$row['CreateDate'],$row['EditDate']);
				$arr[] = $blog;
			}
			return $arr;
		}
		else {
			//die("The query yielded zero results.No rows found.");
		}
	}
}
