<?php
/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen
Date:			12/16/2017
Description:	Creates the DAL class for  eventcomment table and respective stored procedures

*/



class Eventcomment {

    // This is for local purposes only! In hosted environments the db_settings.php file should be outside of the webroot, such as: include("/outside-webroot/db_settings.php");
    protected static function getDbSettings() { return "DAL/db_localsettings.php"; }

    /******************************************************************/
    // Properties
    /******************************************************************/

    protected $Id;
    protected $Comment;
    protected $CustomerId;
    protected $EventCommentStatusTypeId;
    protected $EventId;
    protected $CreateDate;
    protected $EditDate;


    /******************************************************************/
    // Constructors
    /******************************************************************/
    public function __construct() {
        $argv = func_get_args();
        switch( func_num_args() ) {
            case 0:
                self::__constructBase();
                break;
            case 1:
                self::__constructPK( $argv[0] );
                break;
            case 7:
                self::__constructFull( $argv[0], $argv[1], $argv[2], $argv[3], $argv[4], $argv[5], $argv[6] );
        }
    }


    public function __constructBase() {
        $this->Id = 0;
        $this->Comment = "";
        $this->CustomerId = 0;
        $this->EventCommentStatusTypeId = 0;
        $this->EventId = 0;
        $this->CreateDate = "";
        $this->EditDate = "";
    }


    public function __constructPK($paramId) {
        $this->load($paramId);
    }


    public function __constructFull($paramId,$paramComment,$paramCustomerId,$paramEventCommentStatusTypeId,$paramEventId,$paramCreateDate,$paramEditDate) {
        $this->Id = $paramId;
        $this->Comment = $paramComment;
        $this->CustomerId = $paramCustomerId;
        $this->EventCommentStatusTypeId = $paramEventCommentStatusTypeId;
        $this->EventId = $paramEventId;
        $this->CreateDate = $paramCreateDate;
        $this->EditDate = $paramEditDate;
    }


    /******************************************************************/
    // Accessors / Mutators
    /******************************************************************/

    public function getId(){
        return $this->Id;
    }
    public function setId($value){
        $this->Id = $value;
    }
    public function getComment(){
        return $this->Comment;
    }
    public function setComment($value){
        $this->Comment = $value;
    }
    public function getCustomerId(){
        return $this->CustomerId;
    }
    public function setCustomerId($value){
        $this->CustomerId = $value;
    }
    public function getEventCommentStatusTypeId(){
        return $this->EventCommentStatusTypeId;
    }
    public function setEventCommentStatusTypeId($value){
        $this->EventCommentStatusTypeId = $value;
    }
    public function getEventId(){
        return $this->EventId;
    }
    public function setEventId($value){
        $this->EventId = $value;
    }
    public function getCreateDate(){
        return $this->CreateDate;
    }
    public function setCreateDate($value){
        $this->CreateDate = $value;
    }
    public function getEditDate(){
        return $this->EditDate;
    }
    public function setEditDate($value){
        $this->EditDate = $value;
    }


    /******************************************************************/
    // Public Methods
    /******************************************************************/


    public function load($paramId) {
        include(self::getDbSettings());
        $conn = new mysqli($servername, $username, $password, $dbname);
        $stmt = $conn->prepare('CALL usp_eventcomment_Load(?)');
        $stmt->bind_param('i', $paramId);
        $stmt->execute();

        $result = $stmt->get_result();
        if (!$result) die($conn->error);

        while ($row = $result->fetch_assoc()) {
            $this->setId($row['Id']);
            $this->setComment($row['Comment']);
            $this->setCustomerId($row['CustomerId']);
            $this->setEventCommentStatusTypeId($row['EventCommentStatusTypeId']);
            $this->setEventId($row['EventId']);
            $this->setCreateDate($row['CreateDate']);
            $this->setEditDate($row['EditDate']);
        }
    }


    public function save() {
        if ($this->getId() == 0)
            $this->insert();
        else
            $this->update();
    }

    /******************************************************************/
    // Private Methods
    /******************************************************************/



    private function insert() {
        include(self::getDbSettings());
        $conn = new mysqli($servername, $username, $password, $dbname);
        $stmt = $conn->prepare('CALL usp_eventcomment_Add(?,?,?,?,?,?)');
        $arg1 = $this->getComment();
        $arg2 = $this->getCustomerId();
        $arg3 = $this->getEventCommentStatusTypeId();
        $arg4 = $this->getEventId();
        $arg5 = $this->getCreateDate();
        $arg6 = $this->getEditDate();
        $stmt->bind_param('siiiss',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6);
        $stmt->execute();

        $result = $stmt->get_result();
        if (!$result) die($conn->error);
        while ($row = $result->fetch_assoc()) {
            // By default, the DALGen generated INSERT procedure returns the scope identity as id
            $this->load($row['id']);
        }
    }


    private function update() {
        include(self::getDbSettings());
        $conn = new mysqli($servername, $username, $password, $dbname);
        $stmt = $conn->prepare('CALL usp_eventcomment_Update(?,?,?,?,?,?,?)');
        $arg1 = $this->getId();
        $arg2 = $this->getComment();
        $arg3 = $this->getCustomerId();
        $arg4 = $this->getEventCommentStatusTypeId();
        $arg5 = $this->getEventId();
        $arg6 = $this->getCreateDate();
        $arg7 = $this->getEditDate();
        $stmt->bind_param('isiiiss',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7);
        $stmt->execute();
    }

    private static function setNullValue($value){
        if ($value == "")
            return null;
        else
            return $value;
    }

    /******************************************************************/
    // Static Methods
    /******************************************************************/



    public static function loadall() {
        include(self::getDbSettings());
        $conn = new mysqli($servername, $username, $password, $dbname);
        $stmt = $conn->prepare('CALL usp_eventcomment_LoadAll()');
        $stmt->execute();

        $result = $stmt->get_result();
        if (!$result) die($conn->error);
        if ($result->num_rows > 0) {
            $arr = array();
            while ($row = $result->fetch_assoc()) {
                $eventcomment = new Eventcomment($row['Id'],$row['Comment'],$row['CustomerId'],$row['EventCommentStatusTypeId'],$row['EventId'],$row['CreateDate'],$row['EditDate']);
                $arr[] = $eventcomment;
            }
            return $arr;
        }
        else {
            //die("The query yielded zero results.No rows found.");
        }
    }


    public static function remove($paramId) {
        include(self::getDbSettings());
        $conn = new mysqli($servername, $username, $password, $dbname);
        $stmt = $conn->prepare('CALL usp_eventcomment_Delete(?)');
        $stmt->bind_param('i', $paramId);
        $stmt->execute();
    }


    public static function search($paramId,$paramComment,$paramCustomerId,$paramEventCommentStatusTypeId,$paramEventId,$paramCreateDate,$paramEditDate) {
        include(self::getDbSettings());
        $conn = new mysqli($servername, $username, $password, $dbname);
        $stmt = $conn->prepare('CALL usp_eventcomment_Search(?,?,?,?,?,?,?)');
        $arg1 = Eventcomment::setNullValue($paramId);
        $arg2 = Eventcomment::setNullValue($paramComment);
        $arg3 = Eventcomment::setNullValue($paramCustomerId);
        $arg4 = Eventcomment::setNullValue($paramEventCommentStatusTypeId);
        $arg5 = Eventcomment::setNullValue($paramEventId);
        $arg6 = Eventcomment::setNullValue($paramCreateDate);
        $arg7 = Eventcomment::setNullValue($paramEditDate);
        $stmt->bind_param('isiiiss',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7);
        $stmt->execute();

        $result = $stmt->get_result();
        if (!$result) die($conn->error);
        if ($result->num_rows > 0) {
            $arr = array();
            while ($row = $result->fetch_assoc()) {
                $eventcomment = new Eventcomment($row['Id'],$row['Comment'],$row['CustomerId'],$row['EventCommentStatusTypeId'],$row['EventId'],$row['CreateDate'],$row['EditDate']);
                $arr[] = $eventcomment;
            }
            return $arr;
        }
        else {
            //die("The query yielded zero results.No rows found.");
        }
    }
    public static function loadbyeventid($paramEventId) {
        include(self::getDbSettings());
        $conn = new mysqli($servername, $username, $password, $dbname);
        $stmt = $conn->prepare('CALL usp_eventcomment_LoadByEventId(?)');
        $stmt->bind_param('i', $paramEventId);
        $stmt->execute();
        $result = $stmt->get_result();
        if (!$result) die($conn->error);
        if ($result->num_rows > 0) {
            $arr = array();
            while ($row = $result->fetch_assoc()) {
                $eventcomment = new Eventcomment($row['Id'],$row['Comment'],$row['CustomerId'],$row['EventCommentStatusTypeId'],$row['EventId'],$row['CreateDate'],$row['EditDate']);
                $arr[] = $eventcomment;
            }
            return $arr;
        }
        else {
            //echo "The query yielded zero results.No rows found.";
        }
    }
}
