<?php
/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			12/12/2017
Description:	Creates the DAL class for  item table and respective stored procedures

*/



class Item {

	// This is for local purposes only! In hosted environments the db_settings.php file should be outside of the webroot, such as: include("/outside-webroot/db_settings.php");
	protected static function getDbSettings() { return "DAL/db_localsettings.php"; }

	/******************************************************************/
	// Properties
	/******************************************************************/

	protected $Id;
	protected $Name;
	protected $Description;
	protected $ImgUrl;
	protected $Price;
	protected $ItemTypeId;
	protected $ItemStatusTypeId;
	protected $CreateDate;
	protected $Rating;


	/******************************************************************/
	// Constructors
	/******************************************************************/
	public function __construct() {
		$argv = func_get_args();
		switch( func_num_args() ) {
			case 0:
				self::__constructBase();
				break;
			case 1:
				self::__constructPK( $argv[0] );
				break;
			case 9:
				self::__constructFull( $argv[0], $argv[1], $argv[2], $argv[3], $argv[4], $argv[5], $argv[6], $argv[7], $argv[8] );
		}
	}


	public function __constructBase() {
		$this->Id = 0;
		$this->Name = "";
		$this->Description = "";
		$this->ImgUrl = "";
		$this->Price = 0;
		$this->ItemTypeId = 0;
		$this->ItemStatusTypeId = 0;
		$this->CreateDate = "";
		$this->Rating = 0;
	}


	public function __constructPK($paramId) {
		$this->load($paramId);
	}


	public function __constructFull($paramId,$paramName,$paramDescription,$paramImgUrl,$paramPrice,$paramItemTypeId,$paramItemStatusTypeId,$paramCreateDate,$paramRating) {
		$this->Id = $paramId;
		$this->Name = $paramName;
		$this->Description = $paramDescription;
		$this->ImgUrl = $paramImgUrl;
		$this->Price = $paramPrice;
		$this->ItemTypeId = $paramItemTypeId;
		$this->ItemStatusTypeId = $paramItemStatusTypeId;
		$this->CreateDate = $paramCreateDate;
		$this->Rating = $paramRating;
	}


	/******************************************************************/
	// Accessors / Mutators
	/******************************************************************/

	public function getId(){
		return $this->Id;
	}
	public function setId($value){
		$this->Id = $value;
	}
	public function getName(){
		return $this->Name;
	}
	public function setName($value){
		$this->Name = $value;
	}
	public function getDescription(){
		return $this->Description;
	}
	public function setDescription($value){
		$this->Description = $value;
	}
	public function getImgUrl(){
		return $this->ImgUrl;
	}
	public function setImgUrl($value){
		$this->ImgUrl = $value;
	}
	public function getPrice(){
		return $this->Price;
	}
	public function setPrice($value){
		$this->Price = $value;
	}
	public function getItemTypeId(){
		return $this->ItemTypeId;
	}
	public function setItemTypeId($value){
		$this->ItemTypeId = $value;
	}
	public function getItemStatusTypeId(){
		return $this->ItemStatusTypeId;
	}
	public function setItemStatusTypeId($value){
		$this->ItemStatusTypeId = $value;
	}
	public function getCreateDate(){
		return $this->CreateDate;
	}
	public function setCreateDate($value){
		$this->CreateDate = $value;
	}
	public function getRating(){
		return $this->Rating;
	}
	public function setRating($value){
		$this->Rating = $value;
	}


	/******************************************************************/
	// Public Methods
	/******************************************************************/


	public function load($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_item_Load(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);

		while ($row = $result->fetch_assoc()) {
		 $this->setId($row['Id']);
		 $this->setName($row['Name']);
		 $this->setDescription($row['Description']);
		 $this->setImgUrl($row['ImgUrl']);
		 $this->setPrice($row['Price']);
		 $this->setItemTypeId($row['ItemTypeId']);
		 $this->setItemStatusTypeId($row['ItemStatusTypeId']);
		 $this->setCreateDate($row['CreateDate']);
		 $this->setRating($row['Rating']);
		}
	}


	public function save() {
		if ($this->getId() == 0)
			$this->insert();
		else
			$this->update();
	}

	/******************************************************************/
	// Private Methods
	/******************************************************************/



	private function insert() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_item_Add(?,?,?,?,?,?,?,?)');
		$arg1 = $this->getName();
		$arg2 = $this->getDescription();
		$arg3 = $this->getImgUrl();
		$arg4 = $this->getPrice();
		$arg5 = $this->getItemTypeId();
		$arg6 = $this->getItemStatusTypeId();
		$arg7 = $this->getCreateDate();
		$arg8 = $this->getRating();
		$stmt->bind_param('sssdiisd',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7,$arg8);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		while ($row = $result->fetch_assoc()) {
			// By default, the DALGen generated INSERT procedure returns the scope identity as id
			$this->load($row['id']);
		}
	}


	private function update() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_item_Update(?,?,?,?,?,?,?,?,?)');
		$arg1 = $this->getId();
		$arg2 = $this->getName();
		$arg3 = $this->getDescription();
		$arg4 = $this->getImgUrl();
		$arg5 = $this->getPrice();
		$arg6 = $this->getItemTypeId();
		$arg7 = $this->getItemStatusTypeId();
		$arg8 = $this->getCreateDate();
		$arg9 = $this->getRating();
		$stmt->bind_param('isssdiisd',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7,$arg8,$arg9);
		$stmt->execute();
	}

	private static function setNullValue($value){
		if ($value == "")
			return null;
		else
			return $value;
	}

	/******************************************************************/
	// Static Methods
	/******************************************************************/



	public static function loadall() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_item_LoadAll()');
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$item = new Item($row['Id'],$row['Name'],$row['Description'],$row['ImgUrl'],$row['Price'],$row['ItemTypeId'],$row['ItemStatusTypeId'],$row['CreateDate'],$row['Rating']);
				$arr[] = $item;
			}
			return $arr;
		}
		else {
			//die("The query yielded zero results.No rows found.");
		}
	}


	public static function remove($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_item_Delete(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();
	}


	public static function search($paramId,$paramName,$paramDescription,$paramImgUrl,$paramPrice,$paramItemTypeId,$paramItemStatusTypeId,$paramCreateDate,$paramRating) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_item_Search(?,?,?,?,?,?,?,?,?)');
		$arg1 = Item::setNullValue($paramId);
		$arg2 = Item::setNullValue($paramName);
		$arg3 = Item::setNullValue($paramDescription);
		$arg4 = Item::setNullValue($paramImgUrl);
		$arg5 = Item::setNullValue($paramPrice);
		$arg6 = Item::setNullValue($paramItemTypeId);
		$arg7 = Item::setNullValue($paramItemStatusTypeId);
		$arg8 = Item::setNullValue($paramCreateDate);
		$arg9 = Item::setNullValue($paramRating);
		$stmt->bind_param('isssdiisd',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7,$arg8,$arg9);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$item = new Item($row['Id'],$row['Name'],$row['Description'],$row['ImgUrl'],$row['Price'],$row['ItemTypeId'],$row['ItemStatusTypeId'],$row['CreateDate'],$row['Rating']);
				$arr[] = $item;
			}
			return $arr;
		}
		else {
			//die("The query yielded zero results.No rows found.");
		}
	}
}
