<?php
/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			1/4/2018
Description:	Creates the DAL class for  portfolioitem table and respective stored procedures

*/



class Portfolioitem {

	// This is for local purposes only! In hosted environments the db_settings.php file should be outside of the webroot, such as: include("/outside-webroot/db_settings.php");
	protected static function getDbSettings() { return "DAL/db_localsettings.php"; }

	/******************************************************************/
	// Properties
	/******************************************************************/

	protected $Id;
	protected $Name;
	protected $Description;
	protected $ProjectUrl;
	protected $ImageUrl;
	protected $PortfolioCategoryId;
	protected $CreateDate;


	/******************************************************************/
	// Constructors
	/******************************************************************/
	public function __construct() {
		$argv = func_get_args();
		switch( func_num_args() ) {
			case 0:
				self::__constructBase();
				break;
			case 1:
				self::__constructPK( $argv[0] );
				break;
			case 7:
				self::__constructFull( $argv[0], $argv[1], $argv[2], $argv[3], $argv[4], $argv[5], $argv[6] );
		}
	}


	public function __constructBase() {
		$this->Id = 0;
		$this->Name = "";
		$this->Description = "";
		$this->ProjectUrl = "";
		$this->ImageUrl = "";
		$this->PortfolioCategoryId = 0;
		$this->CreateDate = "";
	}


	public function __constructPK($paramId) {
		$this->load($paramId);
	}


	public function __constructFull($paramId,$paramName,$paramDescription,$paramProjectUrl,$paramImageUrl,$paramPortfolioCategoryId,$paramCreateDate) {
		$this->Id = $paramId;
		$this->Name = $paramName;
		$this->Description = $paramDescription;
		$this->ProjectUrl = $paramProjectUrl;
		$this->ImageUrl = $paramImageUrl;
		$this->PortfolioCategoryId = $paramPortfolioCategoryId;
		$this->CreateDate = $paramCreateDate;
	}


	/******************************************************************/
	// Accessors / Mutators
	/******************************************************************/

	public function getId(){
		return $this->Id;
	}
	public function setId($value){
		$this->Id = $value;
	}
	public function getName(){
		return $this->Name;
	}
	public function setName($value){
		$this->Name = $value;
	}
	public function getDescription(){
		return $this->Description;
	}
	public function setDescription($value){
		$this->Description = $value;
	}
	public function getProjectUrl(){
		return $this->ProjectUrl;
	}
	public function setProjectUrl($value){
		$this->ProjectUrl = $value;
	}
	public function getImageUrl(){
		return $this->ImageUrl;
	}
	public function setImageUrl($value){
		$this->ImageUrl = $value;
	}
	public function getPortfolioCategoryId(){
		return $this->PortfolioCategoryId;
	}
	public function setPortfolioCategoryId($value){
		$this->PortfolioCategoryId = $value;
	}
	public function getCreateDate(){
		return $this->CreateDate;
	}
	public function setCreateDate($value){
		$this->CreateDate = $value;
	}


	/******************************************************************/
	// Public Methods
	/******************************************************************/


	public function load($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_portfolioitem_Load(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);

		while ($row = $result->fetch_assoc()) {
		 $this->setId($row['Id']);
		 $this->setName($row['Name']);
		 $this->setDescription($row['Description']);
		 $this->setProjectUrl($row['ProjectUrl']);
		 $this->setImageUrl($row['ImageUrl']);
		 $this->setPortfolioCategoryId($row['PortfolioCategoryId']);
		 $this->setCreateDate($row['CreateDate']);
		}
	}


	public function save() {
		if ($this->getId() == 0)
			$this->insert();
		else
			$this->update();
	}

	/******************************************************************/
	// Private Methods
	/******************************************************************/



	private function insert() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_portfolioitem_Add(?,?,?,?,?,?)');
		$arg1 = $this->getName();
		$arg2 = $this->getDescription();
		$arg3 = $this->getProjectUrl();
		$arg4 = $this->getImageUrl();
		$arg5 = $this->getPortfolioCategoryId();
		$arg6 = $this->getCreateDate();
		$stmt->bind_param('ssssis',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		while ($row = $result->fetch_assoc()) {
			// By default, the DALGen generated INSERT procedure returns the scope identity as id
			$this->load($row['id']);
		}
	}


	private function update() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_portfolioitem_Update(?,?,?,?,?,?,?)');
		$arg1 = $this->getId();
		$arg2 = $this->getName();
		$arg3 = $this->getDescription();
		$arg4 = $this->getProjectUrl();
		$arg5 = $this->getImageUrl();
		$arg6 = $this->getPortfolioCategoryId();
		$arg7 = $this->getCreateDate();
		$stmt->bind_param('issssis',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7);
		$stmt->execute();
	}

	private static function setNullValue($value){
		if ($value == "")
			return null;
		else
			return $value;
	}

	/******************************************************************/
	// Static Methods
	/******************************************************************/



	public static function loadall() {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_portfolioitem_LoadAll()');
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$portfolioitem = new Portfolioitem($row['Id'],$row['Name'],$row['Description'],$row['ProjectUrl'],$row['ImageUrl'],$row['PortfolioCategoryId'],$row['CreateDate']);
				$arr[] = $portfolioitem;
			}
			return $arr;
		}
		else {
			//die("The query yielded zero results.No rows found.");
		}
	}


	public static function remove($paramId) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_portfolioitem_Delete(?)');
		$stmt->bind_param('i', $paramId);
		$stmt->execute();
	}


	public static function search($paramId,$paramName,$paramDescription,$paramProjectUrl,$paramImageUrl,$paramPortfolioCategoryId,$paramCreateDate) {
		include(self::getDbSettings());
		$conn = new mysqli($servername, $username, $password, $dbname);
		$stmt = $conn->prepare('CALL usp_portfolioitem_Search(?,?,?,?,?,?,?)');
		$arg1 = Portfolioitem::setNullValue($paramId);
		$arg2 = Portfolioitem::setNullValue($paramName);
		$arg3 = Portfolioitem::setNullValue($paramDescription);
		$arg4 = Portfolioitem::setNullValue($paramProjectUrl);
		$arg5 = Portfolioitem::setNullValue($paramImageUrl);
		$arg6 = Portfolioitem::setNullValue($paramPortfolioCategoryId);
		$arg7 = Portfolioitem::setNullValue($paramCreateDate);
		$stmt->bind_param('issssis',$arg1,$arg2,$arg3,$arg4,$arg5,$arg6,$arg7);
		$stmt->execute();

		$result = $stmt->get_result();
		if (!$result) die($conn->error);
		if ($result->num_rows > 0) {
			$arr = array();
			while ($row = $result->fetch_assoc()) {
				$portfolioitem = new Portfolioitem($row['Id'],$row['Name'],$row['Description'],$row['ProjectUrl'],$row['ImageUrl'],$row['PortfolioCategoryId'],$row['CreateDate']);
				$arr[] = $portfolioitem;
			}
			return $arr;
		}
		else {
			//die("The query yielded zero results.No rows found.");
		}
	}
    public static function loadbyportfoliocategoryid($paramPortfolioCategoryId) {
        include(self::getDbSettings());
        $conn = new mysqli($servername, $username, $password, $dbname);
        $stmt = $conn->prepare('CALL usp_portfolioitem_LoadByPortfolioCategoryId(?)');
        $stmt->bind_param('i', $paramPortfolioCategoryId);
        $stmt->execute();

        $result = $stmt->get_result();
        if (!$result) die($conn->error);
        if ($result->num_rows > 0) {
            $arr = array();
            while ($row = $result->fetch_assoc()) {
                $portfolioitem = new Portfolioitem($row['Id'],$row['Name'],$row['Description'],$row['ProjectUrl'],$row['ImageUrl'],$row['PortfolioCategoryId'],$row['CreateDate']);
                $arr[] = $portfolioitem;
            }
            return $arr;
        }
        else {
            //die("The query yielded zero results.No rows found.");
        }
    }
}
