/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			12/12/2017
Description:	Creates the itemtype table and respective stored procedures

*/


USE businesstemplate;



-- ------------------------------------------------------------
-- Drop existing objects
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `businesstemplate`.`itemtype`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_itemtype_Load`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_itemtype_LoadAll`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_itemtype_Add`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_itemtype_Update`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_itemtype_Delete`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_itemtype_Search`;


-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `businesstemplate`.`itemtype` (
Id INT AUTO_INCREMENT,
Name VARCHAR(255),
Description VARCHAR(1025),
CONSTRAINT pk_itemtype_Id PRIMARY KEY (Id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_itemtype_Load`
(
	 IN paramId INT
)
BEGIN
	SELECT
		`itemtype`.`Id` AS `Id`,
		`itemtype`.`Name` AS `Name`,
		`itemtype`.`Description` AS `Description`
	FROM `itemtype`
	WHERE 		`itemtype`.`Id` = paramId;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_itemtype_LoadAll`
()
BEGIN
	SELECT
		`itemtype`.`Id` AS `Id`,
		`itemtype`.`Name` AS `Name`,
		`itemtype`.`Description` AS `Description`
	FROM `itemtype`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_itemtype_Add`
(
	 IN paramName VARCHAR(255),
	 IN paramDescription VARCHAR(1025)
)
BEGIN
	INSERT INTO `itemtype` (Name,Description)
	VALUES (paramName, paramDescription);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_itemtype_Update`
(
	IN paramId INT,
	IN paramName VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	UPDATE `itemtype`
	SET Name = paramName
		,Description = paramDescription
	WHERE		`itemtype`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_itemtype_Delete`
(
	IN paramId INT
)
BEGIN
	DELETE FROM `itemtype`
	WHERE		`itemtype`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_itemtype_Search`
(
	IN paramId INT,
	IN paramName VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	SELECT
		`itemtype`.`Id` AS `Id`,
		`itemtype`.`Name` AS `Name`,
		`itemtype`.`Description` AS `Description`
	FROM `itemtype`
	WHERE
		COALESCE(itemtype.`Id`,0) = COALESCE(paramId,itemtype.`Id`,0)
		AND COALESCE(itemtype.`Name`,'') = COALESCE(paramName,itemtype.`Name`,'')
		AND COALESCE(itemtype.`Description`,'') = COALESCE(paramDescription,itemtype.`Description`,'');
END //
DELIMITER ;


