/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			1/7/2018
Description:	Creates the upload table and respective stored procedures

*/


USE businesstemplate;



-- ------------------------------------------------------------
-- Drop existing objects
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `businesstemplate`.`upload`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_upload_Load`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_upload_LoadAll`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_upload_Add`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_upload_Update`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_upload_Delete`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_upload_Search`;


-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `businesstemplate`.`upload` (
Id INT AUTO_INCREMENT,
Url VARCHAR(1024),
CONSTRAINT pk_upload_Id PRIMARY KEY (Id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_upload_Load`
(
	 IN paramId INT
)
BEGIN
	SELECT
		`upload`.`Id` AS `Id`,
		`upload`.`Url` AS `Url`
	FROM `upload`
	WHERE 		`upload`.`Id` = paramId;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_upload_LoadAll`
()
BEGIN
	SELECT
		`upload`.`Id` AS `Id`,
		`upload`.`Url` AS `Url`
	FROM `upload`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_upload_Add`
(
	 IN paramUrl VARCHAR(1024)
)
BEGIN
	INSERT INTO `upload` (Url)
	VALUES (paramUrl);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_upload_Update`
(
	IN paramId INT,
	IN paramUrl VARCHAR(1024)
)
BEGIN
	UPDATE `upload`
	SET Url = paramUrl
	WHERE		`upload`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_upload_Delete`
(
	IN paramId INT
)
BEGIN
	DELETE FROM `upload`
	WHERE		`upload`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_upload_Search`
(
	IN paramId INT,
	IN paramUrl VARCHAR(1024)
)
BEGIN
	SELECT
		`upload`.`Id` AS `Id`,
		`upload`.`Url` AS `Url`
	FROM `upload`
	WHERE
		COALESCE(upload.`Id`,0) = COALESCE(paramId,upload.`Id`,0)
		AND COALESCE(upload.`Url`,'') = COALESCE(paramUrl,upload.`Url`,'');
END //
DELIMITER ;


