/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			12/27/2017
Description:	Creates the orderstatustype table and respective stored procedures

*/


USE businesstemplate;



-- ------------------------------------------------------------
-- Drop existing objects
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `businesstemplate`.`orderstatustype`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_orderstatustype_Load`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_orderstatustype_LoadAll`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_orderstatustype_Add`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_orderstatustype_Update`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_orderstatustype_Delete`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_orderstatustype_Search`;


-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `businesstemplate`.`orderstatustype` (
Id INT AUTO_INCREMENT,
Name VARCHAR(255),
Description VARCHAR(1025),
CONSTRAINT pk_orderstatustype_Id PRIMARY KEY (Id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_orderstatustype_Load`
(
	 IN paramId INT
)
BEGIN
	SELECT
		`orderstatustype`.`Id` AS `Id`,
		`orderstatustype`.`Name` AS `Name`,
		`orderstatustype`.`Description` AS `Description`
	FROM `orderstatustype`
	WHERE 		`orderstatustype`.`Id` = paramId;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_orderstatustype_LoadAll`
()
BEGIN
	SELECT
		`orderstatustype`.`Id` AS `Id`,
		`orderstatustype`.`Name` AS `Name`,
		`orderstatustype`.`Description` AS `Description`
	FROM `orderstatustype`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_orderstatustype_Add`
(
	 IN paramName VARCHAR(255),
	 IN paramDescription VARCHAR(1025)
)
BEGIN
	INSERT INTO `orderstatustype` (Name,Description)
	VALUES (paramName, paramDescription);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_orderstatustype_Update`
(
	IN paramId INT,
	IN paramName VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	UPDATE `orderstatustype`
	SET Name = paramName
		,Description = paramDescription
	WHERE		`orderstatustype`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_orderstatustype_Delete`
(
	IN paramId INT
)
BEGIN
	DELETE FROM `orderstatustype`
	WHERE		`orderstatustype`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_orderstatustype_Search`
(
	IN paramId INT,
	IN paramName VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	SELECT
		`orderstatustype`.`Id` AS `Id`,
		`orderstatustype`.`Name` AS `Name`,
		`orderstatustype`.`Description` AS `Description`
	FROM `orderstatustype`
	WHERE
		COALESCE(orderstatustype.`Id`,0) = COALESCE(paramId,orderstatustype.`Id`,0)
		AND COALESCE(orderstatustype.`Name`,'') = COALESCE(paramName,orderstatustype.`Name`,'')
		AND COALESCE(orderstatustype.`Description`,'') = COALESCE(paramDescription,orderstatustype.`Description`,'');
END //
DELIMITER ;


