/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			12/15/2017
Description:	Creates the blogcategory table and respective stored procedures

*/


USE businesstemplate;



-- ------------------------------------------------------------
-- Drop existing objects
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `businesstemplate`.`blogcategory`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_blogcategory_Load`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_blogcategory_LoadAll`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_blogcategory_Add`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_blogcategory_Update`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_blogcategory_Delete`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_blogcategory_Search`;


-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `businesstemplate`.`blogcategory` (
Id INT AUTO_INCREMENT,
Name VARCHAR(255),
Description VARCHAR(1025),
CONSTRAINT pk_blogcategory_Id PRIMARY KEY (Id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_blogcategory_Load`
(
	 IN paramId INT
)
BEGIN
	SELECT
		`blogcategory`.`Id` AS `Id`,
		`blogcategory`.`Name` AS `Name`,
		`blogcategory`.`Description` AS `Description`
	FROM `blogcategory`
	WHERE 		`blogcategory`.`Id` = paramId;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_blogcategory_LoadAll`
()
BEGIN
	SELECT
		`blogcategory`.`Id` AS `Id`,
		`blogcategory`.`Name` AS `Name`,
		`blogcategory`.`Description` AS `Description`
	FROM `blogcategory`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_blogcategory_Add`
(
	 IN paramName VARCHAR(255),
	 IN paramDescription VARCHAR(1025)
)
BEGIN
	INSERT INTO `blogcategory` (Name,Description)
	VALUES (paramName, paramDescription);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_blogcategory_Update`
(
	IN paramId INT,
	IN paramName VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	UPDATE `blogcategory`
	SET Name = paramName
		,Description = paramDescription
	WHERE		`blogcategory`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_blogcategory_Delete`
(
	IN paramId INT
)
BEGIN
	DELETE FROM `blogcategory`
	WHERE		`blogcategory`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_blogcategory_Search`
(
	IN paramId INT,
	IN paramName VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	SELECT
		`blogcategory`.`Id` AS `Id`,
		`blogcategory`.`Name` AS `Name`,
		`blogcategory`.`Description` AS `Description`
	FROM `blogcategory`
	WHERE
		COALESCE(blogcategory.`Id`,0) = COALESCE(paramId,blogcategory.`Id`,0)
		AND COALESCE(blogcategory.`Name`,'') = COALESCE(paramName,blogcategory.`Name`,'')
		AND COALESCE(blogcategory.`Description`,'') = COALESCE(paramDescription,blogcategory.`Description`,'');
END //
DELIMITER ;


