/*
Author:			This code was generated by DALGen version 1.1.0.0 available at https://github.com/H0r53/DALGen 
Date:			12/9/2017
Description:	Creates the itemstatustype table and respective stored procedures

*/


USE businesstemplate;



-- ------------------------------------------------------------
-- Drop existing objects
-- ------------------------------------------------------------

DROP TABLE IF EXISTS `businesstemplate`.`itemstatustype`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_itemstatustype_Load`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_itemstatustype_LoadAll`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_itemstatustype_Add`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_itemstatustype_Update`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_itemstatustype_Delete`;
DROP PROCEDURE IF EXISTS `businesstemplate`.`usp_itemstatustype_Search`;


-- ------------------------------------------------------------
-- Create table
-- ------------------------------------------------------------



CREATE TABLE `businesstemplate`.`itemstatustype` (
Id INT AUTO_INCREMENT,
Name VARCHAR(255),
Description VARCHAR(1025),
CONSTRAINT pk_itemstatustype_Id PRIMARY KEY (Id)
);


-- ------------------------------------------------------------
-- Create default SCRUD sprocs for this table
-- ------------------------------------------------------------


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_itemstatustype_Load`
(
	 IN paramId INT
)
BEGIN
	SELECT
		`itemstatustype`.`Id` AS `Id`,
		`itemstatustype`.`Name` AS `Name`,
		`itemstatustype`.`Description` AS `Description`
	FROM `itemstatustype`
	WHERE 		`itemstatustype`.`Id` = paramId;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_itemstatustype_LoadAll`
()
BEGIN
	SELECT
		`itemstatustype`.`Id` AS `Id`,
		`itemstatustype`.`Name` AS `Name`,
		`itemstatustype`.`Description` AS `Description`
	FROM `itemstatustype`;
END //
DELIMITER ;

DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_itemstatustype_Add`
(
	 IN paramName VARCHAR(255),
	 IN paramDescription VARCHAR(1025)
)
BEGIN
	INSERT INTO `itemstatustype` (Name,Description)
	VALUES (paramName, paramDescription);
	-- Return last inserted ID as result
	SELECT LAST_INSERT_ID() as id;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_itemstatustype_Update`
(
	IN paramId INT,
	IN paramName VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	UPDATE `itemstatustype`
	SET Name = paramName
		,Description = paramDescription
	WHERE		`itemstatustype`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_itemstatustype_Delete`
(
	IN paramId INT
)
BEGIN
	DELETE FROM `itemstatustype`
	WHERE		`itemstatustype`.`Id` = paramId;
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE `businesstemplate`.`usp_itemstatustype_Search`
(
	IN paramId INT,
	IN paramName VARCHAR(255),
	IN paramDescription VARCHAR(1025)
)
BEGIN
	SELECT
		`itemstatustype`.`Id` AS `Id`,
		`itemstatustype`.`Name` AS `Name`,
		`itemstatustype`.`Description` AS `Description`
	FROM `itemstatustype`
	WHERE
		COALESCE(itemstatustype.`Id`,0) = COALESCE(paramId,itemstatustype.`Id`,0)
		AND COALESCE(itemstatustype.`Name`,'') = COALESCE(paramName,itemstatustype.`Name`,'')
		AND COALESCE(itemstatustype.`Description`,'') = COALESCE(paramDescription,itemstatustype.`Description`,'');
END //
DELIMITER ;


